In [1]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("C:\workspace_Bigdata\DataScience\PART 02 파이썬 분석\csv\iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.shape

(150, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
df['species'].replace({'setosa':0,'versicolor':1,'virginica':2},inplace=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_10024\2484868255.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({'setosa':0,'versicolor':1,'virginica':2},inplace=True)

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [9]:
X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df["species"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=11)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

In [11]:
dt=DecisionTreeClassifier(random_state=11)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [12]:
pred=dt.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,pred)
print(acc)

0.9333333333333333

In [2]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

df=pd.read_csv("PART 02 파이썬 분석\csv\iris.csv")
df['species'].replace({'setosa':0,'versicolor':1,'virginica':2}, inplace=True)

X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df["species"]

C:\Users\user\AppData\Local\Temp\ipykernel_8664\1971638364.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['species'].replace({'setosa':0,'versicolor':1,'virginica':2}, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_8664\1971638364.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({'setosa':0,'versicolor':1,'virginica':2}, inplace=True)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=11)

In [5]:
import sklearn.metrics


dt=DecisionTreeClassifier(random_state=11)
dt.fit(X_train,y_train)
pred=dt.predict(X_test)

from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,pred)
print(acc)

0.9333333333333333

In [6]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  9]], dtype=int64)

In [10]:
from sklearn.metrics import classification_report
rpt=classification_report(y_test,pred)
print(rpt)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30

In [11]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [15]:
df=pd.read_csv("C:/workspace_Bigdata/DataScience/PART 02 파이썬 분석/csv/titanic.csv")

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [18]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
d_mean=df["Age"].mean()
df["Age"].fillna(d_mean,inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_8664\1711239809.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(d_mean,inplace=True)

In [20]:
d_mode=df["Embarked"].mode()[0]
df["Embarked"].fillna(d_mode,inplace=True)

In [21]:
from sklearn.preprocessing import LabelEncoder
df["Sex"]=LabelEncoder().fit_transform(df["Sex"])

In [22]:
from sklearn.preprocessing import LabelEncoder
df["Embarked"]=LabelEncoder().fit_transform(df["Embarked"])

In [23]:
df["FamilySize"]=df["SibSp"]+df["Parch"]

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",1,22.000000,1,0,A/5 21171,7.2500,NaN,2,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.000000,1,0,PC 17599,71.2833,C85,0,1
2,3,1,3,"Heikkinen, Miss. Laina",0,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,2,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.000000,1,0,113803,53.1000,C123,2,1
4,5,0,3,"Allen, Mr. William Henry",1,35.000000,0,0,373450,8.0500,NaN,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.000000,0,0,211536,13.0000,NaN,2,0
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.000000,0,0,112053,30.0000,B42,2,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,29.699118,1,2,W./C. 6607,23.4500,NaN,2,3
889,890,1,1,"Behr, Mr. Karl Howell",1,26.000000,0,0,111369,30.0000,C148,0,0
890,891,0,3,"Dooley, Mr. Patrick",1,32.000000,0,0,370376,7.7500,NaN,1,0

In [25]:
X=df[["Pclass","Sex","Age","Fare","Embarked","FamilySize"]]
y=df["Survived"]

In [27]:
X

     Pclass  Sex        Age     Fare  Embarked  FamilySize
0         3    1  22.000000   7.2500         2           1
1         1    0  38.000000  71.2833         0           1
2         3    0  26.000000   7.9250         2           0
3         1    0  35.000000  53.1000         2           1
4         3    1  35.000000   8.0500         2           0
..      ...  ...        ...      ...       ...         ...
886       2    1  27.000000  13.0000         2           0
887       1    0  19.000000  30.0000         2           0
888       3    0  29.699118  23.4500         2           3
889       1    1  26.000000  30.0000         0           0
890       3    1  32.000000   7.7500         1           0

[891 rows x 6 columns]

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=11)

In [29]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 6)
(179, 6)
(712,)
(179,)

In [30]:
dt=DecisionTreeClassifier(random_state=11)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [31]:
pred=dt.predict(X_test)

In [56]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
pred=knn.predict(X_test)

In [57]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test,pred)
print(mat)

[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]

In [58]:
from sklearn.metrics import classification_report
rpt = classification_report(y_test,pred)
print(rpt)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30

In [32]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,pred)
print(acc)

0.7877094972067039

In [35]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [41]:
df=pd.read_csv("C:\workspace_Bigdata\DataScience\PART 02 파이썬 분석\csv\iris.csv")

In [42]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [44]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [40]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [45]:

df[["sepal_length"]]=scaler.fit_transform(df[["sepal_length"]])
df[["sepal_width"]]=scaler.fit_transform(df[["sepal_width"]])
df[["petal_length"]]=scaler.fit_transform(df[["petal_length"]])
df[["petal_width"]]=scaler.fit_transform(df[["petal_width"]])

In [46]:
X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df["species"]

In [47]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=11)

In [48]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

In [52]:
knn=KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [53]:
pred=knn.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score
acc =accuracy_score(y_test,pred)
print(acc)

0.9333333333333333

In [60]:
#SVM을 이용한 타이타닉 생존자 분류(예측) 분석 수행

import numpy as np
import pandas as pd
import sklearn

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [62]:
df=pd.read_csv("C:/workspace_Bigdata/DataScience/PART 02 파이썬 분석/csv/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
d_mean=df["Age"].mean()
df["Age"].fillna(d_mean,inplace=True)

d_mode=df["Embarked"].mode()[0]
df["Embarked"].fillna(d_mode,inplace=True)

df["FamilySize"]=df["SibSp"]+df["Parch"]

C:\Users\user\AppData\Local\Temp\ipykernel_8664\3749487430.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(d_mean,inplace=True)

In [64]:
onehot_sex=pd.get_dummies(df["Sex"])
df=pd.concat([df,onehot_sex],axis=1)

In [65]:
onehot_embarked=pd.get_dummies(df["Embarked"])
df=pd.concat([df,onehot_embarked],axis=1)

In [66]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,female,male,C,Q,S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,1,False,True,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,1,True,False,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,0,True,False,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,1,True,False,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,0,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,0,False,True,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,0,True,False,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S,3,True,False,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,0,False,True,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,0,False,True,False,True,False

In [67]:
X=df[["Pclass","Age","Fare","FamilySize","female","male","C","Q","S"]]
y=df["Survived"]

In [68]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3, random_state=10)

In [69]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(623, 9)
(268, 9)
(623,)
(268,)

In [1]:
from sklearn.svm import SVC
sv=SVC(kernel="linear",gamma=0.1)
sv.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [75]:
pred=sv.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score
acc =accuracy_score(y_test, pred)
print(acc)

0.7238805970149254

In [77]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, pred)
print(mat)

[[167   7]
 [ 67  27]]

In [78]:
from sklearn.metrics import classification_report
rpt = classification_report(y_test,pred)
print(rpt)

              precision    recall  f1-score   support

           0       0.71      0.96      0.82       174
           1       0.79      0.29      0.42        94

    accuracy                           0.72       268
   macro avg       0.75      0.62      0.62       268
weighted avg       0.74      0.72      0.68       268

# 로지스틱 회귀

In [7]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv("C:/workspace_DataScience/DataScience/PART 02 파이썬 분석/csv/iris.csv")

In [8]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [10]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[["sepal_length"]]=scaler.fit_transform(df[["sepal_length"]])
df[["sepal_width"]]=scaler.fit_transform(df[["sepal_width"]])
df[["petal_length"]]=scaler.fit_transform(df[["petal_length"]])
'df[["petal_width"]]=scaler.fit_transform(df[["petal_width"]])

In [16]:
X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df["species"]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=11)

In [20]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [21]:
lr=LogisticRegression()

In [22]:
lr.fit(X_train,y_train)

LogisticRegression()

In [24]:
pred=lr.predict(X_test)
pred

array(['virginica', 'virginica', 'versicolor', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'setosa', 'virginica', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'setosa', 'virginica'], dtype=object)

In [27]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)
print(acc)

0.8333333333333334

# 랜덤포레스트

In [31]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [32]:
df=pd.read_csv("C:/workspace_DataScience/DataScience/PART 02 파이썬 분석/csv/titanic.csv")

In [33]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [35]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [36]:
d_mean=df["Age"].mean()
df["Age"].fillna(d_mean,inplace=True)

C:\Users\hyeer\AppData\Local\Temp\ipykernel_5380\1711239809.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(d_mean,inplace=True)

In [37]:
d_mode=df["Embarked"].mode()[0]
df["Embarked"].fillna(d_mode,inplace=True)

In [53]:
from sklearn.preprocessing import LabelEncoder
df["Sex"]=LabelEncoder().fit_transform(df["Sex"])

from sklearn.preprocessing import LabelEncoder
df["Embared"]=LabelEncoder().fit_transform(df["Embarked"])

In [39]:
df["FamilySize"]=df["SibSp"]+df["Parch"]

In [42]:
X=df[["Pclass","Sex","Age","Fare","Embarked","FamilySize"]]
y=df["Survived"]

In [54]:
X

     Pclass  Sex        Age     Fare Embarked  FamilySize
0         3    1  22.000000   7.2500        S           1
1         1    0  38.000000  71.2833        C           1
2         3    0  26.000000   7.9250        S           0
3         1    0  35.000000  53.1000        S           1
4         3    1  35.000000   8.0500        S           0
..      ...  ...        ...      ...      ...         ...
886       2    1  27.000000  13.0000        S           0
887       1    0  19.000000  30.0000        S           0
888       3    0  29.699118  23.4500        S           3
889       1    1  26.000000  30.0000        C           0
890       3    1  32.000000   7.7500        Q           0

[891 rows x 6 columns]

In [55]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      891 non-null    int64
 1   Sex         891 non-null    int32
 2   Age         891 non-null    float64
 3   Fare        891 non-null    float64
 4   Embarked    891 non-null    object
 5   FamilySize  891 non-null    int64
dtypes: float64(2), int32(1), int64(2), object(1)
memory usage: 38.4+ KB

In [57]:
from sklearn.preprocessing import LabelEncoder
df["Embarked"]=LabelEncoder().fit_transform(df["Embarked"])

In [60]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      891 non-null    int64
 1   Sex         891 non-null    int32
 2   Age         891 non-null    float64
 3   Fare        891 non-null    float64
 4   Embarked    891 non-null    object
 5   FamilySize  891 non-null    int64
dtypes: float64(2), int32(1), int64(2), object(1)
memory usage: 38.4+ KB

In [52]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=11)

In [45]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 6), (179, 6), (712,), (179,))

In [46]:
rf=RandomForestClassifier(n_estimators=50,max_depth=3,random_state=20)

In [62]:
rf.fit(X_train,y_train)  #Embarked 범주형변수 전처린

ValueError: could not convert string to float: 'S'